server:
  port: 8083

spring:
  data:
    mongodb:
      database: ShareCV
      host: localhost
      port: 27017
      uuid-representation: standard
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}

common:
  rest:
    open-api:
      servers: ${OPEN_AIP_SERVER:http://localhost:8083}
  security:
    use-webflux: ${USE_WEBFLUX:false}
    cors:
      allowed-origins: ${CORS_ORIGINS:https://localhost:8083}
      allowed-methods: ${CORS_METHODS:*}
      allowed-headers: ${CORS_METHODS:*}
    path-matcher:
      permit-all-path-patterns:
        - /webjars/swagger-ui/**
        - /v3/api-docs/**
        - /swagger-resources/**
        - /webjars/**
        - /swagger-ui/**
        - /swagger-ui.html
        - /null/swagger-resources/**
        - /actuator/**
        - /api/v1/company/**
    oauth2-resource-server:
      auth:
        jwk-set-uri: ${KEYCLOAK_URI:https://keycloak.bizzone.unicloud.ai}/auth/realms/${PROFILE_REALM:share-cv-id-backend}/protocol/openid-connect/certs
        issuer-uri: ${KEYCLOAK_URI:https://keycloak.bizzone.unicloud.ai}/auth/realms/${PROFILE_REALM:share-cv-id-backend}